// <auto-generated />
namespace BSFinancial.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class equity4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(equity4));
        
        string IMigrationMetadata.Id
        {
            get { return "201503272016320_equity4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
